# Configuration for travis

language: r

sudo: false

warnings_are_errors: true

r-packages:
  - reticulate
  - rmarkdown
  - Rcpp

r_check_args: --no-vignettes --no-build-vignettes

r_github_packages:
  - r-lib/covr

before_install:
  - pip install --user --upgrade pip
  - pip install --user umap-learn

after_success:
  - Rscript -e 'covr::codecov()'
